### PR TITLE
URA 119 Update BSVI filters and files

### PR DESCRIPTION
**Pull request by Aisha-D**
- Remove old filter no longer used
- Remove exons restricted files
- Add new gene lists
- Add new preferred transcript list
- Add new updated filter list with new gene list
- Remove Global MAF from filters

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/uranus_bsvi_monitor/2)

### CODE REVIEW

**Review by woook — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/uranus_bsvi_monitor/2)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @Aisha-D and @woook)

___
*[`README.md` line 11 at r1](https://reviewable.io/reviews/eastgenomics/uranus_bsvi_monitor/2#-N2qqkd4AJymrBVuKxJ9:-N2qqkd4AJymrBVuKxJA:b5mwhct) ([raw file](https://github.com/eastgenomics/uranus_bsvi_monitor/blob/6cb1470d027718967c43edd0955437ecef8e0cb5/README.md#L11)):*
> ```Markdown
> *  /gene_lists/haem_onc/Lymphoid_v2.0.0.txt
> > Includes genes for the lymphoid panel v2.0.0
> *  /gene_lists/haem_onc/MyeloidAndAcute_v2.0.0.txt
> ```

Aren't these in the wrong order?



_Code quote:_
```Markdown
> Includes genes for the myeloid and acute panel v1.0.0
*  /gene_lists/haem_onc/Lymphoid_v2.0.0.txt
> Includes genes for the lymphoid panel v2.0.0
*  /gene_lists/haem_onc/MyeloidAndAcute_v2.0.0.txt
```

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/uranus_bsvi_monitor/2)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @woook)

___
*[`README.md` line 11 at r1](https://reviewable.io/reviews/eastgenomics/uranus_bsvi_monitor/2#-N2qqkd4AJymrBVuKxJ9:-N2qs-ts5ldwMyAABu8f:b-7v7v3o) ([raw file](https://github.com/eastgenomics/uranus_bsvi_monitor/blob/6cb1470d027718967c43edd0955437ecef8e0cb5/README.md#L11)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

Aren't these in the wrong order?
</blockquote></details>



Looks like its in the right order on normal github view

**Review by woook — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/uranus_bsvi_monitor/2)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @Aisha-D and @woook)

___
*[`README.md` line 11 at r1](https://reviewable.io/reviews/eastgenomics/uranus_bsvi_monitor/2#-N2qqkd4AJymrBVuKxJ9:-N2quHiE78LqXI_8bC3u:bqtdbga) ([raw file](https://github.com/eastgenomics/uranus_bsvi_monitor/blob/6cb1470d027718967c43edd0955437ecef8e0cb5/README.md#L11)):*
<details><summary><i>Previously, Aisha-D wrote…</i></summary><blockquote>



Looks like its in the right order on normal github view

</blockquote></details>

weird, must be a diff bug

**Review by woook — APPROVED** [review]
> Reviewed 1 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/uranus_bsvi_monitor/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Aisha-D)

**Pull request merged**
